### PR TITLE
Move to kotlin build script; Fix shadowing

### LINKED ISSUE #3: Use build.gradle.kts instead of original groovy buildscript
As instroduction of KotlinConf'23, Gradle officially announce now the buildscript language will be Kotlin by default. Hence the buildscript migration is required to avoid future deprecation issues.

### PR DESCRIPTION
**Pull request by juraj-hrivnak**
- Moved the build script to `.kts`.
- Fixed some shadowing issues. I was getting NoClassDefFoundError when using Kotlinx serialization and coroutines before.
- Added Kotlinx serialization core.
- Updated Forge to `14.23.5.2860`.
- Updated to FG5.
- Updated Gradle to `7.2`.

Closes #3

### CODE REVIEW

**Review by ChAoSUnItY — APPROVED** [review]

**Comment by ChAoSUnItY** [comment]
Thanks for the migration!

**Comment by juraj-hrivnak** [comment]
No problem! Do you plan to make a release?

**Comment by ChAoSUnItY** [comment]
Sure, I'll make a release for 1.8.21 after another PR merged.

**Comment by juraj-hrivnak** [comment]
Okay, excellent, thanks!

**Pull request merged**
